version: '3.3'

networks:
  picPayChallengeNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.70.0.0/16

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "aoscir@@123-94847"
    networks:
      picPayChallengeNetwork:
        ipv4_address: 172.70.0.2
    restart: on-failure